### ISSUE TITLE
lkjsdf

### ISSUE THREAD

**Issue by asottile** [asottile-archive/issue-form-test#2]
### your `.pre-commit-config.yaml`

```yaml
ci:
    skip: [terraform-fmt]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: terraform-fmt
        name: terraform fmt
        entry: terraform fmt
        types: [terraform]
        language: system
        pass_filenames: false
```
